# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65vent.proto\"!\n\x0c\x45ventRequest\x12\x11\n\teventName\x18\x01 \x01(\t\"\x18\n\nEventReply\x12\n\n\x02ok\x18\x01 \x01(\x08\x32p\n\x0b\x45ventLogger\x12)\n\tSendEvent\x12\r.EventRequest\x1a\x0b.EventReply\"\x00\x12\x36\n\x14SendEventStreamReply\x12\r.EventRequest\x1a\x0b.EventReply\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_EVENTREQUEST']._serialized_start=15
  _globals['_EVENTREQUEST']._serialized_end=48
  _globals['_EVENTREPLY']._serialized_start=50
  _globals['_EVENTREPLY']._serialized_end=74
  _globals['_EVENTLOGGER']._serialized_start=76
  _globals['_EVENTLOGGER']._serialized_end=188
# @@protoc_insertion_point(module_scope)
